spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/dashboard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:k71110373}
    driver-class-name: com.mysql.cj.jdbc.Driver
